import type { Metadata } from "next";
import type { CSSProperties, ReactNode } from "react";
import "./globals.css";

// System font fallbacks (Google Fonts is unreachable in offline build
// environments; these keep the scaffold's font CSS variables defined).
const fontVariables = {
  "--font-geist-sans":
    "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "--font-geist-mono": "ui-monospace, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
} as CSSProperties;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      style={fontVariables}
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
